# Generated by Django 4.0 on 2024-08-01 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiche', models.ImageField(upload_to='affiches/')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('acteur_principal', models.CharField(max_length=255)),
                ('durée', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.DurationField(auto_created=160)),
                ('salle', models.DecimalField(decimal_places=3, max_digits=5)),
                ('date', models.DateField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cineflix.film')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('username', models.TextField(max_length=255)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('ADMIN', 'Admin')], max_length=30, verbose_name='Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('type', models.TextField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=3, max_digits=6)),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cineflix.projection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cineflix.userprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField(max_length=255)),
                ('nombre_de_place', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cineflix.userprofiles')),
            ],
        ),
        migrations.AddField(
            model_name='projection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cineflix.userprofiles'),
        ),
        migrations.AddField(
            model_name='film',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cineflix.userprofiles'),
        ),
    ]
