# Generated by Django 4.0 on 2024-08-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cineflix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='durée',
            new_name='duree',
        ),
    ]
