# Generated by Django 4.0 on 2024-08-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cineflix', '0002_rename_durée_film_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='user',
        ),
    ]
