# Generated by Django 4.0 on 2024-08-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cineflix', '0003_remove_film_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
