# Generated by Django 4.0 on 2024-08-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cineflix', '0004_remove_projection_user_remove_salle_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cineflix.salle'),
        ),
    ]
